run:
  timeout: 2m

linters:
  enable:
    - govet
    - staticcheck
    - gofmt
    - goimports
    - revive

linters-settings:
  revive:
    severity: warning
    ignore-generated-header: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
