package domain

import "errors"

var (
	ErrEventNotFound          = errors.New("event not found")
	ErrZoneNotFound           = errors.New("zone not found")
	ErrZoneAlreadyExists      = errors.New("zone already exists")
	ErrInsufficientCapacity   = errors.New("insufficient capacity")
	ErrInvalidQuantity        = errors.New("invalid quantity")
	ErrInvalidCapacity        = errors.New("invalid capacity")
	ErrEventNameRequired      = errors.New("event name required")
	ErrZoneNameRequired       = errors.New("zone name required")
	ErrUsernameRequired       = errors.New("username required")
	ErrUsernameInvalid        = errors.New("username invalid")
	ErrEmailRequired          = errors.New("email required")
	ErrPasswordRequired       = errors.New("password required")
	ErrUsernameTaken          = errors.New("username already exists")
	ErrEmailTaken             = errors.New("email already exists")
	ErrIdempotencyKeyRequired = errors.New("idempotency key required")
	ErrIdempotencyConflict    = errors.New("idempotency conflict")
	ErrHoldNotFound           = errors.New("hold not found")
	ErrHoldExpired            = errors.New("hold expired")
	ErrHoldAlreadyConfirmed   = errors.New("hold already confirmed")
	ErrHoldInvalid            = errors.New("hold invalid")
	ErrEventClosed            = errors.New("event closed")
	ErrEventCancelled         = errors.New("event cancelled")
	ErrInvalidCredentials     = errors.New("invalid credentials")
	ErrUserNotFound           = errors.New("user not found")
	ErrSessionNotFound        = errors.New("session not found")
	ErrUnauthorized           = errors.New("unauthorized")
	ErrRegistrationDisabled   = errors.New("registration disabled")
	ErrInvalidID              = errors.New("invalid id")
)
